name: React CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-devops-app .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/react-devops-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/react-devops-app
          docker stop react-devops-app || true
          docker rm react-devops-app || true
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true
          docker run -d -p 80:80 --name react-devops-app ${{ secrets.DOCKER_USERNAME }}/react-devops-app